"""Update admin and teacher table

Revision ID: 3278c99da995
Revises: 57d4a40e7985
Create Date: 2023-04-18 17:00:38.928377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3278c99da995'
down_revision = '57d4a40e7985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'admin_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teachers', 'teacher_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'teacher_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('admins', 'admin_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
