"""Update admin and teacher table

Revision ID: 57d4a40e7985
Revises: 7770fb784bad
Create Date: 2023-04-18 16:46:33.114296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d4a40e7985'
down_revision = '7770fb784bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('admin_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'admins', ['admin_id'])
    op.add_column('teachers', sa.Column('teacher_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'teachers', ['teacher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'teacher_id')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'admin_id')
    # ### end Alembic commands ###
